[base]

HOST = 'localhost'
PORT = '9000'


[database]

DB_HOST = 'localhost'
DB_PORT = 5432
DB_NAME = 'postgres'
DB_USER = 'admin'
DB_PASS = 'admin'

#[redis]
#
#REDIS_HOST = 'localhost'
#REDIS_PORT = 6379