"""init

Revision ID: b01f3000a621
Revises: 
Create Date: 2023-01-22 11:00:22.175189

"""
import datetime
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b01f3000a621'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('name', sa.String(length=64), nullable=False),
                    sa.Column('surname', sa.String(length=64), nullable=False),
                    sa.Column('login', sa.String(length=64), nullable=False),
                    sa.Column('password', sa.String(length=128), nullable=False),
                    sa.Column('birthdate', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('login'),
                    sa.UniqueConstraint('login')
                    )
    op.create_table('rights',
                    sa.Column('user_login', sa.String(length=64), nullable=False),
                    sa.Column('blocked', sa.Boolean(), nullable=True),
                    sa.Column('admin', sa.Boolean(), nullable=True),
                    sa.Column('readonly', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['user_login'], ['users.login'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('user_login')
                    )

    op.create_unique_constraint(None, 'users', ['login'])

    ### end of gen db Alembic commands optional admin inserts below  ###

    # op.bulk_insert('users', [{'name': 'admin',
    #                           'surname': 'admin',
    #                           'login': 'admin',
    #                           'password': '$2b$12$SEAH2.BHCTp/4joKUeVQ9.3hFbN0lXqX9Gvn0aCKyT5mrSUGJXZle',
    #                           'birthdate': datetime.date(1970, 1, 1)}])
    #
    # op.bulk_insert('rights', [{"user_login": 'admin',
    #                            "blocked": False,
    #                            "admin": True,
    #                            "readonly": False}])

    op.execute(
        "INSERT INTO users VALUES ('admin', 'admin', 'admin', '$2b$12$CAuybhSGJbCsU0tMNkfhMuCf61Isd.ld8s7TGb4nLYmBa3vmk5.WG', '1970-01-01 00:00:00.000')")
    op.execute("INSERT INTO rights VALUES ('admin', false, true, false)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rights')
    op.drop_table('users')

    # ### end Alembic commands ###
